---
- name: Manage Docker containers and initialize MongoDB replica set
  hosts: localhost
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Start Docker container node1
      docker_container:
        name: node1
        image: oimon
        state: started
        ports:
          - 27017:27017
        volumes:
          - my_data:/data
        networks:
          - name: mongonetwork
        command: mongod --replSet myReplicaSet --bind_ip localhost,node1
    - name: Start Docker container node2
      docker_container:
        name: node2
        image: oimon
        state: started
        ports:
          - 27018:27017
        volumes:
          - my_data:/data
        networks:
          - name: mongonetwork
        command: mongod --replSet myReplicaSet --bind_ip localhost,node2
    - name: Start Docker container node3
      docker_container:
        name: node3
        image: oimon
        state: started
        ports:
          - 27019:27017
        volumes:
          - my_data:/data
        networks:
          - name: mongonetwork
        command: mongod --replSet myReplicaSet --bind_ip localhost,node3
    - name: Initialize MongoDB replica set
      community.mongodb.mongodb_replicaset:
        replica_set: myReplicaSet
        members:
          - host: node1:27017
          - host: node2:27017
          - host: node3:27017
